### ISSUE TITLE
Unnecessary server calls?

### ISSUE THREAD

**Issue by roidy** [sualfred/script.embuary.info#66]
https://github.com/sualfred/script.embuary.info/blob/ebd175683cf582d3ce56decc505a5f874fb4e61a/resources/lib/tmdb.py#L42-L48

I could be wrong but doesn't this  "if" block need an

```
else:
  break
```

Otherwise if the api call is successful the loop will keep repeating the api call all 4 times?

**Comment by sualfred** [comment]
lol. you are totally right

**Comment by sualfred** [comment]
fixed
