### ISSUE TITLE
Next Aired (Embuary) will not load.

### ISSUE THREAD

**Issue by SnakeATWAR** [sualfred/script.embuary.info#67]
I have an issue where Next Aired will not load per the title.
Here's my full log file: https://pastebin.com/cgbdYSAZ
Any help or advice would be greatly appreciated.
Thanks!

**Comment by sualfred** [comment]
Cannot reproduce it. 
Please try to disable the caching in the addon settings, restart Kodi and give it another shot. Maybe the caching DB is messed up.

**Comment by SnakeATWAR** [comment]
I managed to figure it out. IMO. Once I installed the Next Up addon the tab started working. Personally, I'd add it to the dependencies list since it's a feature that's built into the skin. Thanks for looking into it and apologies for not updating this myself once I figured it out.

**Comment by sualfred** [comment]
This script has nothing to do with the Next Up addon.

**Comment by sualfred** [comment]
Is it possible that u had no library items? Because I can reproduce this issue with a empty DB.

**Comment by SnakeATWAR** [comment]
I see. I am pretty sure I had a library database as I was looking for my next episode of an in progress show (didn't have any streaming addons installed). I'll see if I can reproduce it within the next few days.
